version: "3.1"

services:
  client:
    build: "./client"
    volumes:
      - "./client:/home/node/app"
    working_dir: "/home/node/app"
    command: "yarn serve"
    ports:
      - 8080:8080
      - 8000:8000
